#!/bin/sh

cd /wikiteam3/wikiteam3

# Delete our old data-dump
rm /pokeclicker-wiki-backup/data-dump -r
# Generate our new data
dumpgenerator --xmlrevisions --xml --api=https://pokeclicker.miraheze.org/w/api.php --path=/pokeclicker-wiki-backup/dat>

# Split the xml up
cd /pokeclicker-wiki-backup
node index.js

# Push changes to GitHub
git add .
git commit -am "updated data"
git push
