#!/bin/sh

cd /wikiteam3/wikiteam3

# Delete our old data-dump
rm /pokeclicker-wiki-backup/data-dump -r

# Generate our new data
dumpgenerator --xmlrevisions --xml --api=https://pokeclicker.miraheze.org/w/api.php --path=/pokeclicker-wiki-backup/data-dump

# Delete our old data
rm /pokeclicker-wiki-backup/data -r

# Split the xml up
cd /pokeclicker-wiki-backup
node index.js

# Move the data
cp /pokeclicker-wiki-backup/data-dump/siteinfo.json /pokeclicker-wiki-backup/data/siteinfo.json

# Push changes to GitHub
git add .
git commit -am "updated data"
git push

# Delete our data-dump (free up space)
rm /pokeclicker-wiki-backup/data-dump -r

# log the date
echo "Data backed up"
date
