version: "3"
services:
  pokeclicker-wiki-backup:
    build: .
    container_name: pokeclicker-wiki-backup
    command: ["crond", "-f"]
    networks:
      - proxy
    volumes:
      - ./.ssh:/root/.ssh/
    working_dir: /wikiteam3/wikiteam3
    restart: unless-stopped

networks:
  proxy:
    external: true

# After creation run: ssh-keygen -t rsa -b 4096 -C backup@pokeclicker.com
# this will create your ssh keys

# Get your key using this: cat ~/.ssh/id_rsa.pub
# Then add the key to the deploy key section of your repo

# run the following to test if it worked: ssh -T git@github.com
# ensure you are not running origin as an https reference, must be a git@github.com (ssh) reference

# Run the following:
# git clone git@github.com:RedSparr0w/pokeclicker-wiki-backup.git
# npm i
# git config --global user.email "backup@pokeclicker.com"
# git config --global user.name "auto-backup"

# test that you have push access: git push -f
